version: '3.4'

services:
#  app:
#    build:
#      context: .
#    ports:
#      - "8080:8087"
#    depends_on:
#      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: tasksBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data