server:
  port: 9000
spring:
  output.ansi.enabled: ALWAYS
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            require-authorization-consent: true
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8086/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8086/tm"
              scopes:
                - "openid"
                - "profile"
logging:
  level:
    org:
      springframework:
        security: trace





